### ISSUE TITLE
Fails to build with `undefined reference to `BamTools::BamReader::Open(…)`

### ISSUE THREAD

**Issue by paulmenzel** [sahlenlab/HiCapTools#1]
Using commit 9c55c95 (tag: v1.3.2, Bug fix:Empty bin addition in BackgroundFrequency), building the project fails with the error below.

```
$ mkdir build
$ cd build/
$ cmake ../
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /dev/shm/HiCapTools/build
$ make -j100
Scanning dependencies of target HiCapTools
[  3%] Building CXX object CMakeFiles/HiCapTools.dir/src/CallHiCUP.cpp.o
[ 16%] Building CXX object CMakeFiles/HiCapTools.dir/src/ProbeFeatureClass.cpp.o
[ 16%] Building CXX object CMakeFiles/HiCapTools.dir/src/DesignProbes.cpp.o
[ 16%] Building CXX object CMakeFiles/HiCapTools.dir/src/Find_Interactions.cpp.o
[ 16%] Building CXX object CMakeFiles/HiCapTools.dir/src/Probes.cpp.o
[ 20%] Building CXX object CMakeFiles/HiCapTools.dir/src/Features.cpp.o
[ 23%] Building CXX object CMakeFiles/HiCapTools.dir/src/Proximities.cpp.o
[ 30%] Building CXX object CMakeFiles/HiCapTools.dir/src/ProxDetectMain.cpp.o
[ 30%] Building CXX object CMakeFiles/HiCapTools.dir/src/BackgroundInteractionFrequency.cpp.o
[ 33%] Building CXX object CMakeFiles/HiCapTools.dir/src/RepeatOverlaps.cpp.o
[ 40%] Building CXX object CMakeFiles/HiCapTools.dir/src/NegativeProbeDesign.cpp.o
[ 40%] Building CXX object CMakeFiles/HiCapTools.dir/src/ProcessPairs.cpp.o
[ 46%] Building CXX object CMakeFiles/HiCapTools.dir/src/bioioMod.cpp.o
[ 46%] Building CXX object CMakeFiles/HiCapTools.dir/src/ProbeDesignMain.cpp.o
[ 50%] Building CXX object CMakeFiles/HiCapTools.dir/src/main.cpp.o
[ 53%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/dataanalysis.cpp.o
[ 56%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/fasttransforms.cpp.o
[ 63%] Building CXX object CMakeFiles/HiCapTools.dir/src/RESitesCount.cpp.o
[ 63%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/diffequations.cpp.o
[ 66%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/integration.cpp.o
[ 70%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/linalg.cpp.o
[ 73%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/alglibinternal.cpp.o
[ 76%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/alglibmisc.cpp.o
[ 80%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/statistics.cpp.o
[ 83%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/optimization.cpp.o
[ 86%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/solvers.cpp.o
[ 90%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/ap.cpp.o
[ 93%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/interpolation.cpp.o
[ 96%] Building CXX object CMakeFiles/HiCapTools.dir/ExterAlg/specialfunctions.cpp.o
[100%] Linking CXX executable ../bin/HiCapTools
CMakeFiles/HiCapTools.dir/src/ProcessPairs.cpp.o: In function `ProcessBAM::Initialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int)':
ProcessPairs.cpp:(.text+0xb2): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ProcessPairs.cpp:(.text+0x1d3): undefined reference to `BamTools::BamReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
ProcessPairs.cpp:(.text+0x2be): undefined reference to `BamTools::BamReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/HiCapTools.dir/src/ProcessPairs.cpp.o: In function `ProcessBAM::ProcessSortedBamFile_NegCtrls(ProbeSet&, RESitesClass&, ProximityClass&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, FeatureClass&)':
ProcessPairs.cpp:(.text+0x4c4): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/HiCapTools.dir/src/ProcessPairs.cpp.o: In function `ProcessBAM::ProcessSortedBAMFile(ProbeSet&, RESitesClass&, ProximityClass&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, FeatureClass&)':
ProcessPairs.cpp:(.text+0x112e): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/HiCapTools.dir/build.make:825: ../bin/HiCapTools] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/HiCapTools.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

So, it looks like the header files under `include/api/` are not complete.

**Comment by paulmenzel** [comment]
The actual command by CMake looks like below (`make VERBOSE=1`).

    /usr/bin/cmake -E cmake_link_script CMakeFiles/HiCapTools.dir/link.txt --verbose=1
    /usr/bin/c++    -rdynamic CMakeFiles/HiCapTools.dir/src/BackgroundInteractionFrequency.cpp.o CMakeFiles/HiCapTools.dir/src/CallHiCUP.cpp.o CMakeFiles/HiCapTools.dir/src/DesignProbes.cpp.o CMakeFiles/HiCapTools.dir/src/Features.cpp.o CMakeFiles/HiCapTools.dir/src/Find_Interactions.cpp.o CMakeFiles/HiCapTools.dir/src/NegativeProbeDesign.cpp.o CMakeFiles/HiCapTools.dir/src/ProbeDesignMain.cpp.o CMakeFiles/HiCapTools.dir/src/ProbeFeatureClass.cpp.o CMakeFiles/HiCapTools.dir/src/Probes.cpp.o CMakeFiles/HiCapTools.dir/src/ProcessPairs.cpp.o CMakeFiles/HiCapTools.dir/src/ProxDetectMain.cpp.o CMakeFiles/HiCapTools.dir/src/Proximities.cpp.o CMakeFiles/HiCapTools.dir/src/RESitesCount.cpp.o CMakeFiles/HiCapTools.dir/src/RepeatOverlaps.cpp.o CMakeFiles/HiCapTools.dir/src/bioioMod.cpp.o CMakeFiles/HiCapTools.dir/src/main.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/alglibinternal.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/alglibmisc.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/ap.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/dataanalysis.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/diffequations.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/fasttransforms.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/integration.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/interpolation.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/linalg.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/optimization.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/solvers.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/specialfunctions.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/statistics.cpp.o  -o ../bin/HiCapTools ../bamtools/libbamtools.so.2.4.1 -lz

**Comment by paulmenzel** [comment]
I wonder, why there is `add_library(libbamtools STATIC IMPORTED)` in `CMakeLists.txt` instead of `SHARED`. The library seems to be a shared library.

    $ file bamtools/libbamtools.so.2.4.1
    bamtools/libbamtools.so.2.4.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped

But changing that line, doesn’t make any difference.

**Comment by paulmenzel** [comment]
By the way, the included bamtools library seems to contain the references, the linker does not find.

```
$ nm bamtools/libbamtools.so.2.4.1 | c++filt | grep BamReader::Open
0000000000023180 T BamTools::BamReader::Open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000023190 T BamTools::BamReader::OpenIndex(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

In our system, we have bamtools 2.5.1 and the static library. I was able to link everything with the command below.

    /usr/bin/c++    -rdynamic CMakeFiles/HiCapTools.dir/src/BackgroundInteractionFrequency.cpp.o CMakeFiles/HiCapTools.dir/src/CallHiCUP.cpp.o CMakeFiles/HiCapTools.dir/src/DesignProbes.cpp.o CMakeFiles/HiCapTools.dir/src/Features.cpp.o CMakeFiles/HiCapTools.dir/src/Find_Interactions.cpp.o CMakeFiles/HiCapTools.dir/src/NegativeProbeDesign.cpp.o CMakeFiles/HiCapTools.dir/src/ProbeDesignMain.cpp.o CMakeFiles/HiCapTools.dir/src/ProbeFeatureClass.cpp.o CMakeFiles/HiCapTools.dir/src/Probes.cpp.o CMakeFiles/HiCapTools.dir/src/ProcessPairs.cpp.o CMakeFiles/HiCapTools.dir/src/ProxDetectMain.cpp.o CMakeFiles/HiCapTools.dir/src/Proximities.cpp.o CMakeFiles/HiCapTools.dir/src/RESitesCount.cpp.o CMakeFiles/HiCapTools.dir/src/RepeatOverlaps.cpp.o CMakeFiles/HiCapTools.dir/src/bioioMod.cpp.o CMakeFiles/HiCapTools.dir/src/main.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/alglibinternal.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/alglibmisc.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/ap.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/dataanalysis.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/diffequations.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/fasttransforms.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/integration.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/interpolation.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/linalg.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/optimization.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/solvers.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/specialfunctions.cpp.o CMakeFiles/HiCapTools.dir/ExterAlg/statistics.cpp.o  -o ../bin/HiCapTools -L /package/sequencer/bamtools/2.5.1/lib64/ -lbamtools -lz

So, instead of `../bamtools/libbamtools.so.2.4.1` I used `-L /package/sequencer/bamtools/2.5.1/lib64/ -lbamtools`.

**Comment by jwakely** [comment]
> By the way, the included bamtools library seems to contain the references, the linker does not find.

No it doesn't, that's a different symbol. Read it more carefully.

You need to read https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
